---
framework: mocha
preRun:
     command:
        - yarn
        - yarn lint
        - yarn build
preMerge:
  pattern:
    - "./test/*_test.js"
postMerge:
  pattern: 
    - "./test/*_test.js"
postRun:
     command:
        - yarn --version
version: 1.0
