---
framework: mocha
preRun:
     command:
        - yarn
        - yarn lint
        - yarn build
preMerge:
  pattern:
    - "./test/*.js"
    - "./test/*.ts"
postMerge:
  pattern: 
    - "./test/*.js"
    - "./test/*.ts"
postRun:
     command:
        - yarn --version
version: 1.0
