---
framework: mocha
preRun:
     command:
        - yarn
        - yarn lint
        - yarn build
preMerge:
  pattern:
    - 'test/*test*.js'
    - 'test/*test*.ts'
postMerge:
  pattern: 
    - 'test/*test*.js'
    - 'test/*test*.ts'
postRun:
     command:
        - yarn --version
configFile: .mocharc.yaml
version: 1.0
